`define ST(x) `"x`"
`define CHECK_EQUAL(val, exp) \
    assert(exp==val) else $fatal  ("\n\t%s == %s: 0x%0h != 0x%0h\n", `ST(val), `ST(exp), val, exp);

`define HW_WRITE(name, idx, val) \
            ``name``_we``idx <= 1'b1; \
            ``name``_wdata``idx <= val; \
            @(posedge clk); \
            ``name``_we``idx <= '0;

`define HW_COUNT(name, idx, dir) \
            ``name``_``dir````idx <= 1'b1; \
            @(posedge clk); \
            ``name``_``dir````idx <= 1'b0; \

`define HW_COUNT_VAL(name, idx, dir, val) \
            ``name``_``dir````idx <= 1'b1; \
            ``name``_``dir``value``idx <= val; \
            @(posedge clk); \
            ``name``_``dir````idx <= 1'b0; \

`define SW_READ(sw_addr) \
            valid <= 1'b1; \
            read <= 1'b1; \
            addr <= sw_addr; \
            @(posedge clk); \
            valid <= 1'b0;

`define SW_WRITE(sw_addr, sw_data) \
            valid <= 1'b1; \
            read <= 1'b0; \
            addr <= sw_addr; \
            wdata <= sw_data; \
            wmask <= '1; \
            @(posedge clk); \
            valid <= 1'b0;

// This file was autogenerated by PeakRDL-verilog
module ctrl_rf_tb #(
    parameter                                ADDR_OFFSET = 'h0,  // Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   // Width of SW address bus
    parameter                                DATA_WIDTH  = 32    // Width of SW data bus
);
    // Clocks and resets
    logic                              clk;
    logic                              resetn;

    // Register CONTROL
    logic                     [ 0: 0] CONTROL_start_q;
    logic                     [ 1: 1] CONTROL_input_ready_q;
    logic                     [ 2: 2] CONTROL_weight_ready_q;

    // Register STATUS
    logic                             STATUS_out_ready_we;
    logic                             STATUS_out_ready_wel;
    logic                     [ 0: 0] STATUS_out_ready_wdata;
    logic                             STATUS_out_count_we;
    logic                             STATUS_out_count_wel;
    logic                     [16: 1] STATUS_out_count_wdata;

    // Register Bus
    logic                             valid;    // active high
    logic                             read;     // indicates request is a read
    logic            [ADDR_WIDTH-1:0] addr;     // address (byte aligned, absolute address)
    logic            [DATA_WIDTH-1:0] wdata;    // write data
    logic          [DATA_WIDTH/8-1:0] wmask;    // write mask
    logic            [DATA_WIDTH-1:0] rdata;    // read data

    initial begin
        resetn <= 1'b0;
        #20 @(posedge clk) resetn <= 1'b1;
        $display("%t: TB: reset complete", $time());
    end
    initial begin
        clk <= 1'b0;
        forever #5 clk <= ~clk;
    end

    ctrl_rf_rf #(
        .ADDR_OFFSET(ADDR_OFFSET),
        .ADDR_WIDTH (ADDR_WIDTH),
        .DATA_WIDTH (DATA_WIDTH)
    ) dut (.*);

    initial begin
        logic                  carry;
        logic [DATA_WIDTH-1:0] temp;
        logic [DATA_WIDTH-1:0] value;

        // init all hw inputs
        STATUS_out_ready_wr <= '0;
        STATUS_out_ready_wdata <= '0;
        STATUS_out_count_wr <= '0;
        STATUS_out_count_wdata <= '0;

        // init all sw input
        valid <= '0;
        read <= '0;
        addr <= '0;
        wdata <= '0;
        wmask <= '1;

        @(posedge resetn);
        repeat(5) @(posedge clk);
        $display("%t: Testcase (CONTROL_start ):", $time());
        $display("%t:\tSoftware write (hardware read) test", $time());
        for (int IDX = 0; IDX <= 0; ++IDX) begin

            temp = '0;
            temp[ 0: 0] = CONTROL_start_q;
            temp = (1 << IDX);
            value = '0;

            `SW_WRITE( 0, (1 << IDX) )
            #1 `CHECK_EQUAL(CONTROL_start_q, temp[ 0: 0])

            `SW_WRITE( 0, 0 )
            #1 `CHECK_EQUAL(CONTROL_start_q, value[ 0: 0])

        end
        repeat(5) @(posedge clk);
        $display("%t: Testcase (CONTROL_input_ready ):", $time());
        $display("%t:\tSoftware write (hardware read) test", $time());
        for (int IDX = 1; IDX <= 1; ++IDX) begin

            temp = '0;
            temp[ 1: 1] = CONTROL_input_ready_q;
            temp = (1 << IDX);
            value = '0;

            `SW_WRITE( 0, (1 << IDX) )
            #1 `CHECK_EQUAL(CONTROL_input_ready_q, temp[ 1: 1])

            `SW_WRITE( 0, 0 )
            #1 `CHECK_EQUAL(CONTROL_input_ready_q, value[ 1: 1])

        end
        repeat(5) @(posedge clk);
        $display("%t: Testcase (CONTROL_weight_ready ):", $time());
        $display("%t:\tSoftware write (hardware read) test", $time());
        for (int IDX = 2; IDX <= 2; ++IDX) begin

            temp = '0;
            temp[ 2: 2] = CONTROL_weight_ready_q;
            temp = (1 << IDX);
            value = '0;

            `SW_WRITE( 0, (1 << IDX) )
            #1 `CHECK_EQUAL(CONTROL_weight_ready_q, temp[ 2: 2])

            `SW_WRITE( 0, 0 )
            #1 `CHECK_EQUAL(CONTROL_weight_ready_q, value[ 2: 2])

        end
        repeat(5) @(posedge clk);
        $display("%t: Testcase (STATUS_out_ready ):", $time());
        $display("%t:\tHardware write test", $time());
        for (int IDX = 0; IDX <= 0; ++IDX) begin

            `HW_WRITE( STATUS_out_ready, , (1 << (IDX-0)) )
            `SW_READ( 4 )
            `CHECK_EQUAL(rdata[ 0: 0], (1 << (IDX-0)))

            `HW_WRITE( STATUS_out_ready, , 0 )
            `SW_READ( 4 )
            `CHECK_EQUAL(rdata[ 0: 0], 0)

        end
        repeat(5) @(posedge clk);
        $display("%t: Testcase (STATUS_out_count ):", $time());
        $display("%t:\tHardware write test", $time());
        for (int IDX = 1; IDX <= 16; ++IDX) begin

            `HW_WRITE( STATUS_out_count, , (1 << (IDX-1)) )
            `SW_READ( 4 )
            `CHECK_EQUAL(rdata[16: 1], (1 << (IDX-1)))

            `HW_WRITE( STATUS_out_count, , 0 )
            `SW_READ( 4 )
            `CHECK_EQUAL(rdata[16: 1], 0)

        end

        #200;
        $display("%t: TB: test complete", $time());
        $display("\n\t\t===================");
        $display(  "\t\t=   TEST PASSED   =");
        $display(  "\t\t===================\n");
        $finish();
    end

endmodule: ctrl_rf_tb
