// This file was autogenerated by PeakRDL-verilog
module ctrl_rf_rf #(
    parameter                                ADDR_OFFSET = 0,  //! Module's offset in the main address map
    parameter                                ADDR_WIDTH  = 32,   //! Width of SW address bus
    parameter                                DATA_WIDTH  = 32    //! Width of SW data bus
)(
    // Clocks and resets
    input logic                              clk,     //! Default clock
    input logic                              resetn,  //! Default reset

    // Register CONTROL
    output logic                     [ 0: 0] CONTROL_start_q,              //! Current field value
    output logic                     [ 0: 0] CONTROL_input_ready_q,              //! Current field value
    output logic                     [ 0: 0] CONTROL_weight_ready_q,              //! Current field value

    // Register STATUS
    input  logic                     [ 0: 0] STATUS_out_ready_wdata,          //! HW write data
    input  logic                     [15: 0] STATUS_out_count_wdata,          //! HW write data

    // Register Bus
    input  logic                             valid,    //! Active high valid
    input  logic                             read,     //! Indicates request is a read
    input  logic            [ADDR_WIDTH-1:0] addr,     //! Address (byte aligned, absolute address)
    /* verilator lint_off UNUSED */
    input  logic            [DATA_WIDTH-1:0] wdata,    //! Write data
    input  logic          [DATA_WIDTH/8-1:0] wmask,    //! Write mask
    /* verilator lint_on UNUSED */
    output logic            [DATA_WIDTH-1:0] rdata     //! Read data
);

/* verilator lint_off UNUSED */
    // local output signals for fields (unless block outputs)
    // these can be used as references in other fields
    logic                           [ 0: 0] CONTROL_start_next;
    logic                             CONTROL_start_anded;
    logic                             CONTROL_start_ored;
    logic                             CONTROL_start_xored;
    logic                           [ 0: 0] CONTROL_input_ready_next;
    logic                             CONTROL_input_ready_anded;
    logic                             CONTROL_input_ready_ored;
    logic                             CONTROL_input_ready_xored;
    logic                           [ 0: 0] CONTROL_weight_ready_next;
    logic                             CONTROL_weight_ready_anded;
    logic                             CONTROL_weight_ready_ored;
    logic                             CONTROL_weight_ready_xored;
    logic                           [ 0: 0] STATUS_out_ready_q;
    logic                           [ 0: 0] STATUS_out_ready_next;
    logic                             STATUS_out_ready_anded;
    logic                             STATUS_out_ready_ored;
    logic                             STATUS_out_ready_xored;
    logic                           [15: 0] STATUS_out_count_q;
    logic                           [15: 0] STATUS_out_count_next;
    logic                             STATUS_out_count_anded;
    logic                             STATUS_out_count_ored;
    logic                             STATUS_out_count_xored;
/* verilator lint_on UNUSED */

    // ============================================================
    // SW Access logic
    // ============================================================
    logic sw_wr;
    logic sw_rd;
    /* verilator lint_off UNUSED */
    logic [DATA_WIDTH-1:0] sw_mask;
    logic [DATA_WIDTH-1:0] sw_wdata;
    logic [DATA_WIDTH-1:0] sw_rdata;
    logic [DATA_WIDTH-1:0] sw_masked_data;
    /* verilator lint_on UNUSED */

    // convert bus interface to internal sw_* signals
    assign sw_wr    = valid && !read;
    assign sw_rd    = valid &&  read;
    assign sw_wdata = wdata;
    assign rdata    = sw_rdata;

    // convert byte mask to bit mask
    always_comb begin
        int byte_idx;
        for (byte_idx = 0; byte_idx < DATA_WIDTH/8; byte_idx+=1) begin
            sw_mask[8*(byte_idx+1)-1 -: 8] = {8{wmask[byte_idx]}};
        end
    end

    // helpful masked version of data
    assign sw_masked_data = sw_wdata & sw_mask;
    logic                     [DATA_WIDTH-1:0] CONTROL_rdata;
    logic                     [DATA_WIDTH-1:0] STATUS_rdata;

    assign sw_rdata = // or of each register return (masked)
                   CONTROL_rdata | 
                   STATUS_rdata;
            
        
    // ============================================================
    // Register: CONTROL
    //    [ 0: 0]                start: hw=r     sw=w     reset=0x0
    //    [ 1: 1]          input_ready: hw=r     sw=w     reset=0x0
    //    [ 2: 2]         weight_ready: hw=r     sw=w     reset=0x0
    // ============================================================
    logic                  CONTROL_decode;
    logic                  CONTROL_sw_wr;
    logic                  CONTROL_sw_rd;
    logic [DATA_WIDTH-1:0] CONTROL_q;

    assign CONTROL_decode = (addr == (ADDR_OFFSET+'h0+'h0));
    assign CONTROL_sw_wr = sw_wr && CONTROL_decode;
    assign CONTROL_sw_rd = sw_rd && CONTROL_decode;

    always_comb begin
        CONTROL_q = '0;
        CONTROL_q[ 0: 0] = CONTROL_start_q;
        CONTROL_q[ 1: 1] = CONTROL_input_ready_q;
        CONTROL_q[ 2: 2] = CONTROL_weight_ready_q;
    end

    // masked version of return data
    assign CONTROL_rdata = CONTROL_sw_rd ? CONTROL_q : 'b0;

    // ------------------------------------------------------------
    // Field: start
    // ------------------------------------------------------------
    assign CONTROL_start_anded = & CONTROL_start_q;
    assign CONTROL_start_ored  = | CONTROL_start_q;
    assign CONTROL_start_xored = ^ CONTROL_start_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        CONTROL_start_q <= 0;
    end else begin
        // Defined as single pulse, clear value from last cycle
        CONTROL_start_q <= '0;
        // Software write
        if (CONTROL_sw_wr) begin
            CONTROL_start_q <=  sw_masked_data[ 0: 0] | (CONTROL_start_q & ~sw_mask[ 0: 0]);
        end
    end

    // ------------------------------------------------------------
    // Field: input_ready
    // ------------------------------------------------------------
    assign CONTROL_input_ready_anded = & CONTROL_input_ready_q;
    assign CONTROL_input_ready_ored  = | CONTROL_input_ready_q;
    assign CONTROL_input_ready_xored = ^ CONTROL_input_ready_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        CONTROL_input_ready_q <= 0;
    end else begin
        // Defined as single pulse, clear value from last cycle
        CONTROL_input_ready_q <= '0;
        // Software write
        if (CONTROL_sw_wr) begin
            CONTROL_input_ready_q <=  sw_masked_data[ 1: 1] | (CONTROL_input_ready_q & ~sw_mask[ 1: 1]);
        end
    end

    // ------------------------------------------------------------
    // Field: weight_ready
    // ------------------------------------------------------------
    assign CONTROL_weight_ready_anded = & CONTROL_weight_ready_q;
    assign CONTROL_weight_ready_ored  = | CONTROL_weight_ready_q;
    assign CONTROL_weight_ready_xored = ^ CONTROL_weight_ready_q;

    // next hardware value

    //! main storage
    always_ff @ (posedge clk, negedge resetn)
    if (~resetn) begin
        CONTROL_weight_ready_q <= 0;
    end else begin
        // Defined as single pulse, clear value from last cycle
        CONTROL_weight_ready_q <= '0;
        // Software write
        if (CONTROL_sw_wr) begin
            CONTROL_weight_ready_q <=  sw_masked_data[ 2: 2] | (CONTROL_weight_ready_q & ~sw_mask[ 2: 2]);
        end
    end
            
        
    // ============================================================
    // Register: STATUS
    //    [ 0: 0]            out_ready: hw=w     sw=r     reset=0x0
    //    [16: 1]            out_count: hw=w     sw=r     reset=0x0
    // ============================================================
    logic                  STATUS_decode;
    logic                  STATUS_sw_wr;
    logic                  STATUS_sw_rd;
    logic [DATA_WIDTH-1:0] STATUS_q;

    assign STATUS_decode = (addr == (ADDR_OFFSET+'h0+'h4));
    assign STATUS_sw_wr = sw_wr && STATUS_decode;
    assign STATUS_sw_rd = sw_rd && STATUS_decode;

    always_comb begin
        STATUS_q = '0;
        STATUS_q[ 0: 0] = STATUS_out_ready_q;
        STATUS_q[16: 1] = STATUS_out_count_q;
    end

    // masked version of return data
    assign STATUS_rdata = STATUS_sw_rd ? STATUS_q : 'b0;

    // ------------------------------------------------------------
    // Field: out_ready (wire)
    // ------------------------------------------------------------
    assign STATUS_out_ready_anded = & STATUS_out_ready_q;
    assign STATUS_out_ready_ored  = | STATUS_out_ready_q;
    assign STATUS_out_ready_xored = ^ STATUS_out_ready_q;

    // next hardware value
    assign STATUS_out_ready_next = STATUS_out_ready_wdata;
    assign STATUS_out_ready_q = STATUS_out_ready_next;

    // ------------------------------------------------------------
    // Field: out_count (wire)
    // ------------------------------------------------------------
    assign STATUS_out_count_anded = & STATUS_out_count_q;
    assign STATUS_out_count_ored  = | STATUS_out_count_q;
    assign STATUS_out_count_xored = ^ STATUS_out_count_q;

    // next hardware value
    assign STATUS_out_count_next = STATUS_out_count_wdata;
    assign STATUS_out_count_q = STATUS_out_count_next;

endmodule: ctrl_rf_rf
